### ISSUE TITLE
A Javascript error ocurred in the main process

### ISSUE THREAD

**Issue by javierpr0** [leinelissen/aeon#374]
When I download the application for apple silicon and run the application I get the following error:
![Error](https://i.imgur.com/sqqqttg.png)

These are the specifications of my computer:
![Info](https://i.imgur.com/rGb1fBc.png)

**Comment by leinelissen** [comment]
Hey @javierpr0! Thanks for submitting the issue and sorry for the long wait. I've just released a new version `v0.2.22` that should resolve this issue. Can you confirm that this fixes it?

**Comment by klap50** [comment]
same issue with newest version in pop_OS! (debian based distro from System76)

┬─[klap@BM550:~]─[16:02:59]
╰─>$ aeon
[2023-11-19T19:03:05.905Z][autoUpdater] info: Auto-updates enabled.  
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libcrypto.so.1.1: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1259:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at 56743 (/usr/lib/aeon/resources/app/.webpack/main/index.js:8:1119086)
    at n (/usr/lib/aeon/resources/app/.webpack/main/index.js:8:1938364)
